<?php

namespace Proxies\__CG__\DataBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Planets extends \DataBundle\Entity\Planets implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'DataBundle\\Entity\\Planets' . "\0" . 'id', '' . "\0" . 'DataBundle\\Entity\\Planets' . "\0" . 'name', '' . "\0" . 'DataBundle\\Entity\\Planets' . "\0" . 'imageUri', '' . "\0" . 'DataBundle\\Entity\\Planets' . "\0" . 'x', '' . "\0" . 'DataBundle\\Entity\\Planets' . "\0" . 'y', '' . "\0" . 'DataBundle\\Entity\\Planets' . "\0" . 'mineral', '' . "\0" . 'DataBundle\\Entity\\Planets' . "\0" . 'metal', '' . "\0" . 'DataBundle\\Entity\\Planets' . "\0" . 'gas', '' . "\0" . 'DataBundle\\Entity\\Planets' . "\0" . 'type'];
        }

        return ['__isInitialized__', '' . "\0" . 'DataBundle\\Entity\\Planets' . "\0" . 'id', '' . "\0" . 'DataBundle\\Entity\\Planets' . "\0" . 'name', '' . "\0" . 'DataBundle\\Entity\\Planets' . "\0" . 'imageUri', '' . "\0" . 'DataBundle\\Entity\\Planets' . "\0" . 'x', '' . "\0" . 'DataBundle\\Entity\\Planets' . "\0" . 'y', '' . "\0" . 'DataBundle\\Entity\\Planets' . "\0" . 'mineral', '' . "\0" . 'DataBundle\\Entity\\Planets' . "\0" . 'metal', '' . "\0" . 'DataBundle\\Entity\\Planets' . "\0" . 'gas', '' . "\0" . 'DataBundle\\Entity\\Planets' . "\0" . 'type'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Planets $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId(int $id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getName(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setName(string $name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getImageUri(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImageUri', []);

        return parent::getImageUri();
    }

    /**
     * {@inheritDoc}
     */
    public function setImageUri(string $imageUri)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImageUri', [$imageUri]);

        return parent::setImageUri($imageUri);
    }

    /**
     * {@inheritDoc}
     */
    public function getX(): int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getX', []);

        return parent::getX();
    }

    /**
     * {@inheritDoc}
     */
    public function setX(int $x)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setX', [$x]);

        return parent::setX($x);
    }

    /**
     * {@inheritDoc}
     */
    public function getY(): int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getY', []);

        return parent::getY();
    }

    /**
     * {@inheritDoc}
     */
    public function setY(int $y)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setY', [$y]);

        return parent::setY($y);
    }

    /**
     * {@inheritDoc}
     */
    public function getMineral(): float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMineral', []);

        return parent::getMineral();
    }

    /**
     * {@inheritDoc}
     */
    public function setMineral(float $mineral)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMineral', [$mineral]);

        return parent::setMineral($mineral);
    }

    /**
     * {@inheritDoc}
     */
    public function getMetal(): float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMetal', []);

        return parent::getMetal();
    }

    /**
     * {@inheritDoc}
     */
    public function setMetal(float $metal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMetal', [$metal]);

        return parent::setMetal($metal);
    }

    /**
     * {@inheritDoc}
     */
    public function getGas(): float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGas', []);

        return parent::getGas();
    }

    /**
     * {@inheritDoc}
     */
    public function setGas(float $gas)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGas', [$gas]);

        return parent::setGas($gas);
    }

    /**
     * {@inheritDoc}
     */
    public function getType(): \DataBundle\Entity\PlanetTypes
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getType', []);

        return parent::getType();
    }

    /**
     * {@inheritDoc}
     */
    public function setType(\DataBundle\Entity\PlanetTypes $type)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setType', [$type]);

        return parent::setType($type);
    }

}
