<?php

namespace Proxies\__CG__\DataBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Units extends \DataBundle\Entity\Units implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'DataBundle\\Entity\\Units' . "\0" . 'id', '' . "\0" . 'DataBundle\\Entity\\Units' . "\0" . 'name', '' . "\0" . 'DataBundle\\Entity\\Units' . "\0" . 'imageUri', '' . "\0" . 'DataBundle\\Entity\\Units' . "\0" . 'attack', '' . "\0" . 'DataBundle\\Entity\\Units' . "\0" . 'defence', '' . "\0" . 'DataBundle\\Entity\\Units' . "\0" . 'army'];
        }

        return ['__isInitialized__', '' . "\0" . 'DataBundle\\Entity\\Units' . "\0" . 'id', '' . "\0" . 'DataBundle\\Entity\\Units' . "\0" . 'name', '' . "\0" . 'DataBundle\\Entity\\Units' . "\0" . 'imageUri', '' . "\0" . 'DataBundle\\Entity\\Units' . "\0" . 'attack', '' . "\0" . 'DataBundle\\Entity\\Units' . "\0" . 'defence', '' . "\0" . 'DataBundle\\Entity\\Units' . "\0" . 'army'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Units $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId(int $id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getName(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setName(string $name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getImageUri(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImageUri', []);

        return parent::getImageUri();
    }

    /**
     * {@inheritDoc}
     */
    public function setImageUri(string $imageUri)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImageUri', [$imageUri]);

        return parent::setImageUri($imageUri);
    }

    /**
     * {@inheritDoc}
     */
    public function getAttack(): float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAttack', []);

        return parent::getAttack();
    }

    /**
     * {@inheritDoc}
     */
    public function setAttack(float $attack)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAttack', [$attack]);

        return parent::setAttack($attack);
    }

    /**
     * {@inheritDoc}
     */
    public function getDefence(): float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDefence', []);

        return parent::getDefence();
    }

    /**
     * {@inheritDoc}
     */
    public function setDefence(float $defence)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDefence', [$defence]);

        return parent::setDefence($defence);
    }

    /**
     * {@inheritDoc}
     */
    public function getArmy(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArmy', []);

        return parent::getArmy();
    }

    /**
     * {@inheritDoc}
     */
    public function setArmy(\Doctrine\Common\Collections\Collection $army)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArmy', [$army]);

        return parent::setArmy($army);
    }

}
